[package]
name = "eos-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.22"
x86_64 = "0.14.7"
lazy_static = { version = "1.4", features = ["spin_no_std"] }


[build-dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

